# Generated by Django 5.1.5 on 2025-02-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('body', models.CharField(max_length=255, verbose_name="Ma'lumot")),
                ('category', models.CharField(max_length=255, verbose_name='Kategoriyasi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Mahsulotlar',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'Products',
                'managed': True,
            },
        ),
    ]
