# Generated by Django 5.1.5 on 2025-02-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
