# Generated by Django 5.1.5 on 2025-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_remove_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='body',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(default=1, max_length=255, verbose_name='Kim tomonidan'),
            preserve_default=False,
        ),
    ]
